# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=10, unique=True)),
                ('productimg', models.CharField(max_length=200)),
                ('productname', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('jifen', models.IntegerField()),
                ('productnum', models.IntegerField()),
                ('pingjia', models.IntegerField()),
                ('storenums', models.IntegerField()),
                ('product', models.CharField(max_length=200)),
                ('specifics', models.CharField(max_length=100, null=True)),
                ('categoryid', models.CharField(max_length=10)),
                ('dealer', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
